language: php
sudo: false
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
git:
    depth: 1

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

matrix:
  include:
    - php: 7.2
      env:
        - COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update $COMPOSER_FLAGS

script:
  - vendor/phpunit/phpunit/phpunit $PHPUNIT_FLAGS
  - bin/soap-client generate tests/Fixtures/config.yml soap/src/Container -vvv --dest-class=TestNs/Container/SoapClientContainer
  - php tests/example.php
